# basic options
title: Quickstart Guide
author: Sunil Jadhav
email: write2sunil@gmail.com
description: A guide to get quickly started on ownCloud
twitter_username: messwithsunil
github_username:  gitsgulabjamun
linkedin_username: sunil-jadhav-76b90a9


# Build settings
markdown: kramdown
theme: minima
